import Image from 'next/image'
import React, { useState } from 'react';
import { useEffect } from 'react'
import { useTheme } from 'next-themes';

import ThemeButton from '../theme'
import Head from 'next/head';
import { openInNewTab } from '../../utils/newtab';
import packageJson from '../../../package.json';
import Link from 'next/link';

type LayoutProps = {
  children: React.ReactNode,
};

const Layout = ({ children }: LayoutProps): JSX.Element | null => {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme } = useTheme();
  useEffect(() => {
    setMounted(true)
    const use = async () => {
      (await import('tw-elements')).default;
    };
    use();
  }, []);

  if (!mounted) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Tessa Breen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/close-clover.png" />
      </Head>
      <div >
        <div className='flex flex-row pb-4 pt-4 bg-gradient-to-r from-sky-600 to-sky-800 dark:from-seablue dark:to-white '>
          <h1 className={`ml-8 text-3xl dark:text-almost-black text-white font-bold self-center`}>Tessa Breen</h1>
          <div className='flex ml-auto space-x-8 mr-8'>
            <Link
              // type="button"
              data-te-ripple-init
              // onClick={()=> console.log('go to blog page')}
              href="/blog"
              data-te-ripple-color="light"
              class="dark:text-neutral-900 text-white rounded pb-2 pt-2.5 text-lg font-medium leading-normal text-primary transition duration-150 ease-in-out hover:text-primary-600 focus:text-primary-600 focus:outline-none focus:ring-0 active:text-primary-700 dark:hover:bg-neutral-700">
              Blog
            </Link>
            <Image
              src={theme === 'dark' ? '/linkedin.svg' : '/linkedin-white.svg'}
              alt="linkedin"
              width='35'
              height='35'
              onClick={() => openInNewTab('https://linkedin.com/in/tessabreen')}
              className="ml-4 "
            />
            <Image
              src={theme === 'dark' ? '/github.svg' : '/github-white.svg'}
              alt="linkedin"
              width='35'
              height='35'
              onClick={() => openInNewTab('https://github.com/Mynameistessa')}
            />
            <Image
              src={theme === 'dark' ? 'twitter-black.svg' : '/twitter-ivory.svg'}
              alt="twitter"
              width='35'
              height='35'
              onClick={() => openInNewTab('https://twitter.com/mynameistessa3')}
            />
            <ThemeButton />
          </div>
        </div>
        {children}
        <footer className="text-center lg:text-left mt-auto border-t dark:border-white border-almost-black border-dotted">
          <div className="dark:text-white text-neutral-900 text-center p-4" >
            Copyright © 2023 Tessa Breen | Next.js {packageJson.dependencies.next} & Tailwind Elements{packageJson.dependencies['tw-elements']}
          </div>
        </footer>
      </div>
    </>
  )
}

export default Layout;