import Head from 'next/head'
import type { NextPage } from 'next'
import Image from 'next/image'
import { useRouter } from 'next/router'
import React, { useState } from 'react';

import Contents from '../components/dropdown';

import Layout from '../components/Layout/layout';
import CV from './CV';
import Interests from '../components/interests';
import Link from 'next/link';


export default function App() {
  return (
    <Layout>
      <Head>
        <title>Tessa Breen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/close-clover.png" />
      </Head>
      <div className="grid m-8 lg:mb-24">
        Testing
      </div>

    </Layout>
  )
}
