import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import type { NextPage } from 'next'
import { useTheme } from 'next-themes'

// Import Components
import BasicDetails from '../components/WeatherDetails/basicDetails'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const { theme, setTheme } = useTheme()
  return (
    <>
      <Head>
        <title>Tessa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/close-clover.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={`text-lg dark:text-red-100 light: text-neutral-900 ${styles.name}`}>Tessa</h1>
        <BasicDetails />
        <button className="text-neutral-900 dark:text-red-100" onClick={() => {
          setTheme(theme === 'dark' ? 'light' : 'dark')
        }}>
          Toggle theme
        </button>
        <div className={styles.description}>
          {/* <p>
            Testing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p> */}
          {/* <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}
        </div>

        {/* <div className={styles.center}> */}
        {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}
        {/* </div> */}
        {/* 
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
