import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import type { NextPage } from 'next'
import Image from 'next/image'
import { useRouter } from 'next/router'
// import 'tw-elements';
import React, { useState } from 'react';

import Contents from '../components/dropdown'

import Layout from '../components/Layout/layout'
import Link from 'next/link'
import Tabs from '../components/tabs'
import Home from './home'



export default function App() {
  return (
    <Layout>
      <Head>
        <title>Tessa Breen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/close-clover.png" />
      </Head>

      <div className="flex place-content-evenly m-10  justify-center">
        {/* <div className="md:mb-0 mr-5"> */}
        <div className="w-1/3 relative overflow-hidden bg-no-repeat bg-cover mr-5">
          <img
            src="/me.jpg"
            className="rounded-lg"
            alt="Avatar"
          // width="33%"
          />
          <div className="w-1/3 rounded h-auto absolute top-0 right-0 bottom-0 left-0 overflow-hidden bg-fixed opacity-0 hover:opacity-40 transition duration-300 ease-in-out bg-white"></div>
          {/* <div className="text-white absolute top-1/2 left-1/2 origin-center">Cornwall 2022</div> */}
          {/* </div> */}
        </div>
        <p className="text-base text-justify font-sans-pro leading-relaxed mt-0 mb-4 dark:text-white text-neutral-900 ">
          Hi, I'm Tessa.<br />
          I currently work as a Front-End Software Engineer at <a target="_blank" href="https://unity.com" className="underline">Unity Technologies</a>  building an in-house continuous integration system.

        </p>
      </div>
    </Layout>
  )
}
